// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class NotaFiscal
{
    public int Id { get; set; }

    public bool Aberta { get; set; }

    public DateTime DataCriacao { get; set; }

    public DateTime? DataFechamento { get; set; }

    public virtual ICollection<ProdutoNotaFiscal> ProdutoNotaFiscals { get; set; } = new List<ProdutoNotaFiscal>();
}