// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Produto
{
    public string Id { get; set; }

    public string Descricao { get; set; }

    public int Saldo { get; set; }

    public virtual ICollection<ProdutoNotaFiscal> ProdutoNotaFiscals { get; set; } = new List<ProdutoNotaFiscal>();
}