// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class ProdutoNotaFiscal
{
    public long Id { get; set; }

    public string ProdutoId { get; set; }

    public int NotaFiscalId { get; set; }

    public int Quantidade { get; set; }

    public virtual NotaFiscal NotaFiscal { get; set; }

    public virtual Produto Produto { get; set; }
}