// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Repository.Models;

namespace Repository.Context;

public partial class KorpContext : DbContext
{
    public KorpContext(DbContextOptions<KorpContext> options)
        : base(options)
    {
    }

    public virtual DbSet<NotaFiscal> NotaFiscals { get; set; }

    public virtual DbSet<Produto> Produtos { get; set; }

    public virtual DbSet<ProdutoNotaFiscal> ProdutoNotaFiscals { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<NotaFiscal>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__NotaFisc__3214EC07A4BE79D3");

            entity.ToTable("NotaFiscal");

            entity.Property(e => e.Aberta).HasDefaultValue(true);
            entity.Property(e => e.DataCriacao).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Produto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Produto__3214EC07274CC713");

            entity.ToTable("Produto");

            entity.Property(e => e.Id)
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Descricao)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ProdutoNotaFiscal>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProdutoN__3214EC0772D566F8");

            entity.ToTable("ProdutoNotaFiscal");

            entity.Property(e => e.ProdutoId)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.NotaFiscal).WithMany(p => p.ProdutoNotaFiscals)
                .HasForeignKey(d => d.NotaFiscalId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProdutoNo__NotaF__3E52440B");

            entity.HasOne(d => d.Produto).WithMany(p => p.ProdutoNotaFiscals)
                .HasForeignKey(d => d.ProdutoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProdutoNo__Produ__3D5E1FD2");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}